'use client';

/**
 * Script Display Component
 * Shows the generated narrative script with copy to clipboard functionality
 * Supports three formats: Legacy, User Journey, and Technical Architecture
 */

import { useState } from 'react';
import type { NarrativeScript } from '../types';
import { isUserJourneyScript, isTechnicalArchitectureScript, isLegacyScript } from '../types';

interface ScriptDisplayProps {
  script: NarrativeScript;
  projectName: string;
}

export function ScriptDisplay({ script, projectName }: ScriptDisplayProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    let formattedScript = '';

    if (isUserJourneyScript(script)) {
      formattedScript = `# User Journey Demo Script: ${projectName}

## 💥 CHAPTER 1: THE FRICTION (45-60 seconds)
${script.friction}

## 🧠 CHAPTER 2: THE SOCIAL BRAIN (60-75 seconds)
${script.socialBrain}

## 💎 CHAPTER 3: THE DISCOVERY (45-60 seconds)
${script.discovery}

## 🛡️ CHAPTER 4: THE RESOLUTION (30-45 seconds)
${script.resolution}

---
Generated by Aura Narrative Storyboarder
Demo Type: User Journey (Outcome-Focused)
Total estimated duration: 3-4 minutes
`;
    } else if (isTechnicalArchitectureScript(script)) {
      formattedScript = `# Technical Architecture Demo Script: ${projectName}

## 🌍 CHAPTER I: THE CONTEXT (45-60 seconds)
${script.context}

## 🔐 CHAPTER II: THE LOGIC GATE (75-90 seconds)
${script.logicGate}

## ⚙️ CHAPTER III: THE EXECUTION (60-75 seconds)
${script.execution}

## 🏰 CHAPTER IV: THE MOAT (45-60 seconds)
${script.moat}

---
Generated by Aura Narrative Storyboarder
Demo Type: Technical Architecture (Engineering Deep-Dive)
Total estimated duration: 4-5 minutes
`;
    } else {
      // Legacy format
      formattedScript = `# Video Demo Script: ${projectName}

## 🎬 CONTEXT (30-45 seconds)
${script.context}

## ⚠️ PROBLEM (30-45 seconds)
${script.problem}

## 🔧 PROCESS (60-90 seconds)
${script.process}

## ✨ OUTCOME (30-45 seconds)
${script.outcome}

---
Generated by Aura Narrative Storyboarder
Total estimated duration: 2.5-3.5 minutes
`;
    }

    try {
      await navigator.clipboard.writeText(formattedScript);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  // Render User Journey Demo
  if (isUserJourneyScript(script)) {
    return (
      <div className="w-full max-w-4xl mx-auto">
        {/* Header with Copy Button */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
              User Journey Demo Script
            </h2>
            <p className="text-sm text-muted-foreground">Outcome-focused narrative</p>
          </div>
          <button
            onClick={handleCopy}
            className={`px-6 py-3 rounded-lg font-medium transition-all duration-200 flex items-center gap-2 ${
              copied
                ? 'bg-green-600 text-white'
                : 'bg-blue-600 hover:bg-blue-700 text-white'
            }`}
          >
            {copied ? (
              <>
                <svg
                  className="w-5 h-5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M5 13l4 4L19 7"
                  />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg
                  className="w-5 h-5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
                Copy to Clipboard
              </>
            )}
          </button>
        </div>

        {/* Script Chapters */}
        <div className="space-y-6">
          {/* Chapter 1: The Friction */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-red-500">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-3xl">💥</span>
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  CHAPTER 1: THE FRICTION
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  45-60 seconds • The specific pain point
                </p>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                {script.friction}
              </p>
            </div>
          </div>

          {/* Chapter 2: The Social Brain */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-purple-500">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-3xl">🧠</span>
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  CHAPTER 2: THE SOCIAL BRAIN
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  60-75 seconds • The interface + Adversarial Debate
                </p>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                {script.socialBrain}
              </p>
            </div>
          </div>

          {/* Chapter 3: The Discovery */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-yellow-500">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-3xl">💎</span>
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  CHAPTER 3: THE DISCOVERY
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  45-60 seconds • The $25M Delta
                </p>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                {script.discovery}
              </p>
            </div>
          </div>

          {/* Chapter 4: The Resolution */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-green-500">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-3xl">🛡️</span>
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  CHAPTER 4: THE RESOLUTION
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  30-45 seconds • Reciprocal Protection remediation
                </p>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                {script.resolution}
              </p>
            </div>
          </div>
        </div>

        {/* Footer Info */}
        <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
          <p className="text-sm text-blue-800 dark:text-blue-300">
            💡 <strong>Pro Tip:</strong> Use this script with recording tools like{' '}
            <a
              href="https://www.tella.tv"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-blue-600"
            >
              Tella
            </a>{' '}
            or{' '}
            <a
              href="https://www.arcade.software"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-blue-600"
            >
              Arcade
            </a>
            . Total estimated duration: 3-4 minutes. Visual cues in [brackets] guide your screen transitions.
          </p>
        </div>
      </div>
    );
  }

  // Render Technical Architecture Demo
  if (isTechnicalArchitectureScript(script)) {
    return (
      <div className="w-full max-w-4xl mx-auto">
        {/* Header with Copy Button */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
              Technical Architecture Demo Script
            </h2>
            <p className="text-sm text-muted-foreground">Engineering deep-dive</p>
          </div>
          <button
            onClick={handleCopy}
            className={`px-6 py-3 rounded-lg font-medium transition-all duration-200 flex items-center gap-2 ${
              copied
                ? 'bg-green-600 text-white'
                : 'bg-purple-600 hover:bg-purple-700 text-white'
            }`}
          >
            {copied ? (
              <>
                <svg
                  className="w-5 h-5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M5 13l4 4L19 7"
                  />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg
                  className="w-5 h-5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
                Copy to Clipboard
              </>
            )}
          </button>
        </div>

        {/* Script Chapters */}
        <div className="space-y-6">
          {/* Chapter I: The Context */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-blue-500">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-3xl">🌍</span>
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  CHAPTER I: THE CONTEXT
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  45-60 seconds • Why this exists
                </p>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                {script.context}
              </p>
            </div>
          </div>

          {/* Chapter II: The Logic Gate */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-orange-500">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-3xl">🔐</span>
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  CHAPTER II: THE LOGIC GATE
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  75-90 seconds • Why you built it this way
                </p>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                {script.logicGate}
              </p>
            </div>
          </div>

          {/* Chapter III: The Execution */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-purple-500">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-3xl">⚙️</span>
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  CHAPTER III: THE EXECUTION
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  60-75 seconds • Prove you built it
                </p>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                {script.execution}
              </p>
            </div>
          </div>

          {/* Chapter IV: The Moat */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-green-500">
            <div className="flex items-center gap-3 mb-4">
              <span className="text-3xl">🏰</span>
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  CHAPTER IV: THE MOAT
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  45-60 seconds • Why it's hard to copy
                </p>
              </div>
            </div>
            <div className="prose dark:prose-invert max-w-none">
              <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                {script.moat}
              </p>
            </div>
          </div>
        </div>

        {/* Footer Info */}
        <div className="mt-6 p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg">
          <p className="text-sm text-purple-800 dark:text-purple-300">
            💡 <strong>Pro Tip:</strong> Use this script with recording tools like{' '}
            <a
              href="https://www.tella.tv"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-purple-600"
            >
              Tella
            </a>{' '}
            or{' '}
            <a
              href="https://www.arcade.software"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-purple-600"
            >
              Arcade
            </a>
            . Total estimated duration: 4-5 minutes. Visual cues in [brackets] guide your transitions between code and diagrams.
          </p>
        </div>
      </div>
    );
  }

  // Render Legacy Format
  return (
    <div className="w-full max-w-4xl mx-auto">
      {/* Header with Copy Button */}
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
          Your Video Script
        </h2>
        <button
          onClick={handleCopy}
          className={`px-6 py-3 rounded-lg font-medium transition-all duration-200 flex items-center gap-2 ${
            copied
              ? 'bg-green-600 text-white'
              : 'bg-blue-600 hover:bg-blue-700 text-white'
          }`}
        >
          {copied ? (
            <>
              <svg
                className="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg
                className="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                />
              </svg>
              Copy to Clipboard
            </>
          )}
        </button>
      </div>

      {/* Script Sections */}
      <div className="space-y-6">
        {/* Context */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-blue-500">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">🎬</span>
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                CONTEXT
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                30-45 seconds
              </p>
            </div>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {script.context}
            </p>
          </div>
        </div>

        {/* Problem */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-orange-500">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">⚠️</span>
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                PROBLEM
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                30-45 seconds
              </p>
            </div>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {script.problem}
            </p>
          </div>
        </div>

        {/* Process */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-purple-500">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">🔧</span>
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                PROCESS
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                60-90 seconds
              </p>
            </div>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {script.process}
            </p>
          </div>
        </div>

        {/* Outcome */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-green-500">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">✨</span>
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                OUTCOME
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                30-45 seconds
              </p>
            </div>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {script.outcome}
            </p>
          </div>
        </div>
      </div>

      {/* Footer Info */}
      <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
        <p className="text-sm text-blue-800 dark:text-blue-300">
          💡 <strong>Pro Tip:</strong> Use this script with recording tools like{' '}
          <a
            href="https://www.tella.tv"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-blue-600"
          >
            Tella
          </a>{' '}
          or{' '}
          <a
            href="https://www.arcade.software"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-blue-600"
          >
            Arcade
          </a>
          . Total estimated duration: 2.5-3.5 minutes.
        </p>
      </div>
    </div>
  );
}
