'use client';

/**
 * Script Display Component
 * Shows the generated narrative script with copy to clipboard functionality
 */

import { useState } from 'react';
import type { NarrativeScript } from '../types';

interface ScriptDisplayProps {
  script: NarrativeScript;
  projectName: string;
}

export function ScriptDisplay({ script, projectName }: ScriptDisplayProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    // Format the script for copying
    const formattedScript = `# Video Demo Script: ${projectName}

## 🎬 CONTEXT (30-45 seconds)
${script.context}

## ⚠️ PROBLEM (30-45 seconds)
${script.problem}

## 🔧 PROCESS (60-90 seconds)
${script.process}

## ✨ OUTCOME (30-45 seconds)
${script.outcome}

---
Generated by Builder's OS Narrative Storyboarder
Total estimated duration: 2.5-3.5 minutes
`;

    try {
      await navigator.clipboard.writeText(formattedScript);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto">
      {/* Header with Copy Button */}
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
          Your Video Script
        </h2>
        <button
          onClick={handleCopy}
          className={`px-6 py-3 rounded-lg font-medium transition-all duration-200 flex items-center gap-2 ${
            copied
              ? 'bg-green-600 text-white'
              : 'bg-blue-600 hover:bg-blue-700 text-white'
          }`}
        >
          {copied ? (
            <>
              <svg
                className="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg
                className="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                />
              </svg>
              Copy to Clipboard
            </>
          )}
        </button>
      </div>

      {/* Script Sections */}
      <div className="space-y-6">
        {/* Context */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-blue-500">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">🎬</span>
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                CONTEXT
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                30-45 seconds
              </p>
            </div>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {script.context}
            </p>
          </div>
        </div>

        {/* Problem */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-orange-500">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">⚠️</span>
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                PROBLEM
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                30-45 seconds
              </p>
            </div>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {script.problem}
            </p>
          </div>
        </div>

        {/* Process */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-purple-500">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">🔧</span>
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                PROCESS
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                60-90 seconds
              </p>
            </div>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {script.process}
            </p>
          </div>
        </div>

        {/* Outcome */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-green-500">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">✨</span>
            <div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                OUTCOME
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                30-45 seconds
              </p>
            </div>
          </div>
          <div className="prose dark:prose-invert max-w-none">
            <p className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {script.outcome}
            </p>
          </div>
        </div>
      </div>

      {/* Footer Info */}
      <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
        <p className="text-sm text-blue-800 dark:text-blue-300">
          💡 <strong>Pro Tip:</strong> Use this script with recording tools like{' '}
          <a
            href="https://www.tella.tv"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-blue-600"
          >
            Tella
          </a>{' '}
          or{' '}
          <a
            href="https://www.arcade.software"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-blue-600"
          >
            Arcade
          </a>
          . Total estimated duration: 2.5-3.5 minutes.
        </p>
      </div>
    </div>
  );
}
